{'public:adhoc:cosmo50gas': [('snapshot', 'LONG_TYPE'),
                             ('iOrder', 'LONG_TYPE'),  
                             ('mass', 'DOUBLE_TYPE'),
                             ('x', 'DOUBLE_TYPE'),
                             ('y', 'DOUBLE_TYPE'),
                             ('z', 'DOUBLE_TYPE'),
                             ('vx', 'DOUBLE_TYPE'),
                             ('vy', 'DOUBLE_TYPE'), 
                             ('vz', 'DOUBLE_TYPE'), 
                             ('phi', 'DOUBLE_TYPE'),
                             ('rho', 'DOUBLE_TYPE'),
                             ('temp', 'DOUBLE_TYPE'),
                             ('hsmooth', 'DOUBLE_TYPE'), 
                             ('metals', 'DOUBLE_TYPE')]
                             
  'public:adhoc:cosmo50dark': [('snapshot', 'LONG_TYPE'),
                             ('iOrder', 'LONG_TYPE'),  
                             ('mass', 'DOUBLE_TYPE'),
                             ('x', 'DOUBLE_TYPE'),
                             ('y', 'DOUBLE_TYPE'),
                             ('z', 'DOUBLE_TYPE'),
                             ('vx', 'DOUBLE_TYPE'),
                             ('vy', 'DOUBLE_TYPE'), 
                             ('vz', 'DOUBLE_TYPE'), 
                             ('unknown1', 'DOUBLE_TYPE'),
                             ('unknown2', 'DOUBLE_TYPE')],
                            
  'public:adhoc:cosmo50stat': [('snapshot', 'LONG_TYPE'),
                               ('GrpID', 'LONG_TYPE'),
                               ('Ntot', 'LONG_TYPE'),
                               ('Ngas', 'LONG_TYPE'),
                               ('Nstar', 'LONG_TYPE'),
                               ('Ndark', 'LONG_TYPE'),
                               ('Mvir', 'DOUBLE_TYPE'),
                               ('Rvir', 'DOUBLE_TYPE'),
                               ('GasMass', 'DOUBLE_TYPE'),
                               ('StarMass', 'DOUBLE_TYPE'),
                               ('DarkMass', 'DOUBLE_TYPE'),
                               ('Vmax', 'DOUBLE_TYPE'),
                               ('RVmax', 'DOUBLE_TYPE'),
                               ('VelDisp', 'DOUBLE_TYPE'),
                               ('Xc', 'DOUBLE_TYPE'),
                               ('Yc', 'DOUBLE_TYPE'),
                               ('Zc', 'DOUBLE_TYPE'),
                               ('VXc', 'DOUBLE_TYPE'),
                               ('VYc', 'DOUBLE_TYPE'),
                               ('VZc', 'DOUBLE_TYPE'),
                               ('HaloID', 'LONG_TYPE'),
                               ('Contam', 'STRING_TYPE')]
}
